package com.axonect.ee.enterpriseintegration.domain.util;

import com.axonect.ee.enterpriseintegration.domain.service.ReportDefinition;
import com.axonect.ee.enterpriseintegration.domain.service.StreamingReportDefinition;

import java.util.HashMap;
import java.util.Map;

public class ReportDefinitionsRegistry {
    private static final Map<String, ReportDefinition> registry = new HashMap<>();
    private static final Map<String, StreamingReportDefinition> streamingRegistry = new HashMap<>();

    public static void register(String reportType, ReportDefinition definition) {
        registry.put(reportType, definition);
    }

    public static ReportDefinition getDefinition(String reportType) {
        if (!registry.containsKey(reportType)) {
            throw new IllegalArgumentException("No definition registered for report type: " + reportType);
        }
        return registry.get(reportType);
    }

    /**
     * Register a report that is generated by streaming rather than by offset pagination. Streaming
     * definitions live in their own map so the paginated path stays exactly as it was.
     */
    public static void registerStreaming(String reportType, StreamingReportDefinition definition) {
        streamingRegistry.put(reportType, definition);
    }

    public static boolean isStreaming(String reportType) {
        return streamingRegistry.containsKey(reportType);
    }

    public static StreamingReportDefinition getStreamingDefinition(String reportType) {
        StreamingReportDefinition definition = streamingRegistry.get(reportType);
        if (definition == null) {
            throw new IllegalArgumentException(
                    "No streaming definition registered for report type: " + reportType);
        }
        return definition;
    }
}
